### ISSUE TITLE
CROS

### ISSUE THREAD

**Issue by anonymous122912** [AaadityaG/Articles-Hub#5]
Hi bahi
my project is giving me a cros error 
So i forked your repo to test the things out 
I found that it is working properly in your app but when i give my env variables to the project it gives me an error 
I have also add the platforms for both localhost and netlify app.

So can you tell me hovw exacly you set up your appwrite or you have done something different from hitesh sir 
Because i think there is some problem in that.

**Comment by AaadityaG** [comment]
> Hi bahi
> my project is giving me a cros error 
> So i forked your repo to test the things out 
> I found that it is working properly in your app but when i give my env variables to the project it gives me an error 
> I have also add the platforms for both localhost and netlify app.
> 
> So can you tell me hovw exacly you set up your appwrite or you have done something different from hitesh sir 
> Because i think there is some problem in that.
> 
> 

Come to discord I will share Screenshots of all necessary settings
